version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file:
      - ./src/common/envs/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - financelligence

volumes:
   postgres:
      name: financelligence-docker-db

networks:
   financelligence: